name: Pipeline

on:
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]


jobs:
  build_test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      storage:
        image: adobe/s3mock:latest
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        ports:
          - 9090/tcp
          - 9091/tcp
        env:
          initialBuckets: "content,ssr,templates,resources"

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check formatting
        run: yarn check:format

      - name: Build action
        run: yarn build

      - name: Run tests
        run: yarn test

      # Use the action defined in this repository. kind of a
      - name: Run action locally
        uses: ./
        with:
          endpoint: http://localhost:9090/
          key: access_key
          secret: secret_secret
          bucket: css
          directory: src/tests/
          verbose: true



